spring:
  sql:
    schema:
      locations: classpath:/schema.sql
    data:
      locations: classpath:/data.sql
  datasource:
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    datasource:
      name: parogCloud
      generate-unique-name: false